// Generates the guessit-js output schema from committed data:
//   - test/fixtures/corpus-schema-data.json  (types/cardinality/emitted values, from collect-schema-data.mjs)
//   - test/fixtures/python-properties.json    (Python guessit.api.properties() — authoritative enum lists)
// Outputs:
//   - src/schema.ts          (GUESSIT_SCHEMA data + typed GuessItResult interface)
//   - docs/output-schema.json (JSON Schema, draft-07)
// Regenerate with:  node --import tsx scripts/gen-schema.mjs
import { createRequire } from 'module';
import { writeFileSync } from 'fs';
const require = createRequire(import.meta.url);
const corpus = require('../test/fixtures/corpus-schema-data.json');
const pyProps = require('../test/fixtures/python-properties.json');

// Closed-vocabulary properties: emit an `enum`. Everything else is free text /
// numeric / structured (language objects) and gets type-only.
const VALUE_CONSTRAINED = new Set([
  'source', 'screen_size', 'video_codec', 'audio_codec', 'audio_channels',
  'audio_profile', 'video_profile', 'video_api', 'color_depth', 'container',
  'mimetype', 'other', 'edition', 'type', 'scan_type', 'streaming_service',
  'episode_format',
]);
// Properties whose values are Language/Country objects (or their string code).
const LANGUAGE_PROPS = new Set(['language', 'subtitle_language', 'country']);
// Properties whose runtime type needs a friendlier schema than corpus introspection
// infers (e.g. a JS Date renders as an ISO-8601 string in JSON).
const OVERRIDES = {
  date: { ts: 'string | Date', json: { type: 'string', format: 'date-time' } },
};

const TS_BASE = { string: 'string', number: 'number', boolean: 'boolean',
  Language: 'GuessitLanguage', object: 'Record<string, unknown>', null: 'null' };
const JSON_BASE = { string: { type: 'string' }, number: { type: 'number' },
  boolean: { type: 'boolean' }, Language: { $ref: '#/definitions/Language' },
  object: { type: 'object' }, null: { type: 'null' } };

const props = {};
for (const name of Object.keys(corpus).sort()) {
  const c = corpus[name];
  const base = c.types.filter((t) => t !== 'null');
  const isLang = LANGUAGE_PROPS.has(name);
  // enum = union of (1) Python-declared values, (2) corpus-emitted values, and
  // (3) values the CODE can emit (pattern.values) — so the enum is complete even
  // for values no corpus example triggers (e.g. source "Workprint"/"Telecine").
  const pyVals = (pyProps[name] || []).filter((v) => v !== null);
  const enumVals = VALUE_CONSTRAINED.has(name)
    ? [...new Set([...pyVals, ...c.values, ...(c.codeValues || [])])].sort((a, b) => String(a).localeCompare(String(b)))
    : [];
  props[name] = {
    base: isLang ? ['Language'] : (base.length ? base : ['string']),
    array: c.array, scalar: c.scalar,
    enum: enumVals.length ? enumVals : undefined,
  };
}

// ---- src/schema.ts ----
const tsType = (p, name) => {
  if (OVERRIDES[name]) return p.array && p.scalar ? `${OVERRIDES[name].ts} | (${OVERRIDES[name].ts})[]` : OVERRIDES[name].ts;
  let t;
  if (p.enum) t = p.enum.map((v) => typeof v === 'number' ? v : JSON.stringify(v)).join(' | ');
  else t = [...new Set(p.base.map((b) => TS_BASE[b] ?? 'unknown'))].join(' | ');
  if (p.base.includes('Language')) t = 'string | GuessitLanguage';
  if (p.array && p.scalar) return `${t} | (${t})[]`;
  if (p.array) return `(${t})[]`;
  return t;
};
let ts = `// AUTO-GENERATED by scripts/gen-schema.mjs — do not edit by hand.
// Regenerate: node --import tsx scripts/gen-schema.mjs
// Source of truth: test/fixtures/corpus-schema-data.json + python-properties.json.

/** A detected language or country, as guessit renders it. */
export interface GuessitLanguage {
  name?: string;
  alpha3?: string;
  alpha2?: string;
  country?: string | null;
  script?: string | null;
}

/** Machine-readable description of every property guessit-js can emit. */
export interface PropertySchema {
  /** JSON-ish base type(s) of the value. */
  type: Array<'string' | 'number' | 'boolean' | 'Language' | 'object'>;
  /** True if this property can be emitted as an array (multiple values). */
  array: boolean;
  /** True if this property can be emitted as a single scalar. */
  scalar: boolean;
  /** Closed vocabulary of allowed values, when the property is value-constrained. */
  enum?: Array<string | number>;
}

export const GUESSIT_SCHEMA: Record<string, PropertySchema> = ${JSON.stringify(
  Object.fromEntries(Object.entries(props).map(([k, p]) => [k, {
    type: p.base.filter((b) => b !== 'null'),
    array: p.array, scalar: p.scalar,
    ...(p.enum ? { enum: p.enum } : {}),
  }])), null, 2)};

/** Fully-typed guessit-js result. Every key is optional (presence depends on the input). */
export interface GuessItResult {
${Object.keys(props).map((k) => `  ${k}?: ${tsType(props[k], k)};`).join('\n')}
  /** Any future / custom property. */
  [key: string]: unknown;
}
`;
writeFileSync(new URL('../src/schema.ts', import.meta.url), ts);

// ---- docs/output-schema.json (JSON Schema draft-07) ----
const jsonProp = (p, name) => {
  if (OVERRIDES[name]) {
    const j = OVERRIDES[name].json;
    return p.array && p.scalar ? { oneOf: [j, { type: 'array', items: j }] } : j;
  }
  const variant = (single) => {
    if (p.enum) return { ...single, enum: p.enum };
    return single;
  };
  const bases = p.base.map((b) => JSON_BASE[b] ?? {});
  const single = bases.length === 1 ? variant(bases[0])
    : { oneOf: bases.map((b) => p.enum ? { ...b, enum: p.enum } : b) };
  if (p.array && p.scalar) return { oneOf: [single, { type: 'array', items: single }] };
  if (p.array) return { type: 'array', items: single };
  return single;
};
const schema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'https://github.com/opensubtitles/guessit-js/output-schema.json',
  title: 'guessit-js output',
  description: 'Metadata extracted from a release name. Every property is optional; presence depends on the input. Generated from scripts/gen-schema.mjs.',
  type: 'object',
  definitions: {
    Language: {
      type: ['object', 'string'],
      description: 'A language or country. Rendered as a string code or an object with alpha3/alpha2/name/country.',
      properties: {
        name: { type: 'string' }, alpha3: { type: 'string' }, alpha2: { type: 'string' },
        country: { type: ['string', 'null'] }, script: { type: ['string', 'null'] },
      },
    },
  },
  properties: Object.fromEntries(Object.keys(props).map((k) => [k, jsonProp(props[k], k)])),
  additionalProperties: true,
};
writeFileSync(new URL('../docs/output-schema.json', import.meta.url), JSON.stringify(schema, null, 2) + '\n');

console.log('Generated src/schema.ts and docs/output-schema.json for', Object.keys(props).length, 'properties',
  '(' + Object.values(props).filter((p) => p.enum).length, 'with enums)');
